<?php
/**
 * introduction-app.phtml
 * 
 * Is displayed if the Admin-ip and Admin-mail is not set.
 * Called after the App.class.php has been loaded.
 * 
 * @version   1.0
 * @package   op-core
 * @author    Tomoaki Nagahara <tomoaki.nagahara@gmail.com>
 * @copyright 2015 (C) Tomoaki Nagahara All right reserved.
 */
/* @var $this App */

$ip = $_SERVER['REMOTE_ADDR'];
$mail = $mail = isset($_SERVER['SERVER_ADMIN']) ? $_SERVER['SERVER_ADMIN']: 'your-addr@example.com';
$path = $this->ConvertPath('app:/config.inc.php');

?>
<?php include('introduction-head.phtml') ?>
<section>
	<div style="margin:1em; padding:1em;">
		<h1 class="i18n">Please set an Administrator's IP-Address and E-Mail address.</h1>
		<div style="margin-left:1em;">
			<p class="i18n"><b>Admin-IP</b> is a need to a variety of features that are only notify the administrator.</p>
			<p class="i18n"><b>Admin-Mail</b> is when an error occurs in the app, notice to an error by E-Mail.</p>
			<p><b><?= $path ?></b></p>
		</div>
		
		<div style="margin: 1em; padding: 1em; border: 1px solid black;">
		
		//	<span class="i18n">Set Admin's IP-Address.</span><br>
		$this-&gt;SetAdminIP('<span style="color:red; font-weight:bold;"><?= $ip ?></span>');<br/>
		<br/>
		
		//	<span class="i18n">Set Admin's E-Mail address.</span><br/>
		$this-&gt;SetAdminEMail('<span style="color:red; font-weight:bold;"><?= $mail ?></span>');<br/>
		
		</div>
	</div>
</section>
<?php include('introduction-foot.phtml') ?>
