<?php
/**
 * introduction-nginx.phtml
 * 
 * For Nginx web-server's configuration.
 * 
 * @creation  2015-02-??
 * @version   1.0
 * @package   op-core
 * @author    Tomoaki Nagahara <tomoaki.nagahara@gmail.com>
 * @copyright 2015 (C) Tomoaki Nagahara All right reserved.
 */

//	Output default header.
header("content-type: text/html; charset=utf-8");

//	Init
$port = $_SERVER['SERVER_PORT'];
$host = $_SERVER['SERVER_NAME'];
$root = $_SERVER['DOCUMENT_ROOT'];
$index = 'index.php';
$extensions = 'php|phtml|html|css|js';

//	Separate URL-Query.
list($uri,$query) = explode('?',$_SERVER['REQUEST_URI'].'?');

//	Get App path and Admin's E-Mail address.
$app  = rtrim($uri,'/').'/app.php';
$mail = isset($_SERVER['SERVER_ADMIN']) ? $_SERVER['SERVER_ADMIN']: 'your-addr@example.com';

?>
<style>
.blue{
	color: blue;
}
</style>

<h1 class="i18n"><b>Nginx</b>'s settings</h1>
<p class="i18n">Correct the configuration file of <b>Nginx</b>.</p>

<hr/>

<p class="i18n">Major OS configuration file location.</p>

<ul>
	<li>Linux
		<ul>
			<li>Red Hat : /etc/nginx/conf.d/default.conf</li>
			<li>CentOS : /etc/nginx/conf.d/default.conf</li>
			<li>Debian : </li>
			<li>Ubuntu : </li>
		</ul>
	</li>
	<li>BSD
		<ul>
			<li>FreeBSD : </li>
		</ul>
	</li>
	<li>Mac OS X
		<ul>
			<li>MacPorts : /opt/local/nginx/conf.d/default.conf</li>
			<li>Homebrew : </li>
		</ul>
	</li>
	<li>Windows
		<ul>
			<li class="i18n">Unknown</li>
		</ul>
	</li>
</ul>

<hr/>

<p class="i18n">This is generic settings.</p>

<pre>
server {
	listen      <?php print $port ?>;
	server_name <?php print $host ?>;
	root        <?php print $root ?>;
	index       <?php print $index ?>; <i class="blue"># No.1: <span class="i18n">If index.php file is exists, execute of <b>No.2</b></span>.</i>

	<?php if( $uri === '/' ): ?> 
	<i class="blue"># No.2: <span class="i18n">Specify a file extension to controlled from <i>NewWorld</i>.</span></i>
	location ~ \.(<?php print $extensions ?>)$ {
		fastcgi_pass	127.0.0.1:9000;
		fastcgi_param	SCRIPT_FILENAME  $document_root/app.php; <i class="blue"># <span class="i18n">Always <i>app.php</i> is executed.</span></i>
		fastcgi_param	SERVER_ADMIN	 <?php print $mail ?>;
		include			fastcgi_params;
	}
	
	<i class="blue"># <span class="i18n">403 In case of forbidden error. (deny access.)</span></i>
	error_page 403 <?php print rtrim($uri,'/').'/' ?>app.php;
	<?php endif; ?>
	
	<i class="blue"># No.3: <span class="i18n">This app location.</span></i>
	location <?php print $uri ?> {
		if ( !-e $request_filename ) {
			<i class="blue"># <span class="i18n">Forward to <i>No.2</i>.</span></i>
			rewrite (.*) <?php print $app ?> last;
		}
		<?php if( $uri !== '/' ): ?> 
		<i class="blue"># No.2: <span class="i18n">Specify a file extension to controlled from <i>NewWorld</i>.</span></i>
		location ~ \.(<?php print $extensions ?>)$ {
			fastcgi_pass   127.0.0.1:9000;
			fastcgi_param  SCRIPT_FILENAME  $document_root<?php print $uri ?>app.php; <i class="blue"># <span class="i18n">Always app.php is executed.</span></i>
			fastcgi_param  SERVER_ADMIN     <?php print $mail ?>;
			include  fastcgi_params;
		}
		
		<i class="blue"># <span class="i18n">403 In case of forbidden error. (deny access.)</span></i>
		error_page 403 <?php print $uri ?>app.php;
		<?php endif; ?> 
	}
	
	<i class="blue"># <span class="i18n">Deny access to <i>Apache</i> setting file.</span></i>
	location ~ /\.ht {
		deny all;
	}
}
</pre>
<hr/>
