<!DOCTYPE html>
<html lang="en">
<head>
	<meta charset="utf-8">
	
	<meta http-equiv="Content-Type" content="text/html; charset=utf-8">
	<meta http-equiv="Content-Style-Type" content="text/css">
	
	<meta name="keywords" content="OnePiece-Framework">
	<meta name="description" content="OnePiece-Framework will innovate the world of the framework.">
	
	<script type="text/javascript" src="//ajax.googleapis.com/ajax/libs/jquery/1/jquery.min.js"></script>
	<script type="text/javascript" src="//onepiece-framework.com/en/js/i18n.js"></script>
	
	<title>introduction of onepiece-framework's setup.</title>
</head>
<body>
