<?php
/* @var $this App */

//	Init unit name
if( empty($unit_name) ){
	$this->StackError("Unit name is empty.\n Ex: array('unit_name'=>'each-unit-name') ",'en');
	return;
}

switch( $unit_name ){
	case '_self-test':
		$_unit_name = 'selftest';
		break;
		
	case 'credit-card':
		$_unit_name = 'creditcard';
		break;
		
	case 'language':
		$_unit_name = $unit_name;
		break;
		
	default:
	$this->StackError("Does not define this unit name. \($unit_name)\\",'en');
}

?>
<?php $this->Template('op:/Template/jQuery-load.phtml') ?>
<script type="text/javascript" src="//onepiece-framework.com/js/i18n.js"></script>
<div style="margin: 1em;">
	<h1 class="i18n">Please install \<?= $_unit_name ?>\</h1>
	<p  class="i18n">Please execute this command.</p>
	<div style="border: 1px solid black; margin:1em; padding:1em;">
		<code>
			cd <?= $this->ConvertPath('app:/') ?><br/>
			git clone https://github.com/TomoakiNagahara/op-unit-<?= $_unit_name ?>.git <?= $unit_name ?><br/>
		</code>
	</div>
	<p  class="i18n">
		Or Download here =&gt; 
		<a href="https://github.com/TomoakiNagahara/op-unit-<?= $_unit_name ?>/archive/master.zip">
			https://github.com/TomoakiNagahara/op-unit-<?= $_unit_name ?>/archive/master.zip
		</a>
	</p>
	<p class="i18n">And then reload this page.</p>
</div>
<?php
