<?php
/**
 * wizardry.phtml
 * 
 * This template file use at Wizardry.
 * But, Wizardry will obsolete.
 * And will be integrated into the op-unit-selftest.
 * 
 * @version   1.0
 * @package   op-core
 * @author    Tomoaki Nagahara <tomoaki.nagahara@gmail.com>
 * @copyright 2015 (C) Tomoaki Nagahara All right reserved.
 */
/* @var $this App */

//	Get form name for the Form5.
$form_name = $this->Config()->form_name();
?>
<style>
#op-wizardry{
	margin: 1em 0 1em 0;
}

#op-wizardry table{
	border: 1px solid black !important;
	color: black;
}

#op-wizardry table thead th{
	padding: 0.3em 0 0.1em 0;
	color: white;
	background-color: black;
}

#op-wizardry table tbody th{
	padding-left: 1em;
	vertical-align: middle;
}

#op-wizardry table tbody td{
	background-color:white;
	vertical-align: middle;
}

#op-wizardry input{
	font-size: 12pt;
	margin-right: 1em;
}
</style>
<div id="op-wizardry">
	<?php $this->Form()->Start($form_name) ?>
	<table>
		<caption></caption>
		<colgroup/>
		<thead>
			<tr>
				<th colspan=3>
					<span class="big bold">Wizardry</span>
				</th>
			</tr>
		</thead>
		<tbody>
			<tr>
				<td colspan=3>
					<p>Please enter the root password.</p>
				</td>
			</tr>
			<tr>
				<th>
					<?php $this->Form()->Label('user') ?>
				</th>
				<td> : </td>
				<td>
					<?php $this->Form()->Input('user') ?><br/>
					<?php $this->Form()->Error('user') ?>
				</td>
			</tr>
			<tr>
				<th>
					<?php $this->Form()->Label('password') ?>
				</th>
				<td> : </td>
				<td> 
					<?php $this->Form()->Input('password') ?><br/>
					<?php $this->Form()->Error('password') ?>
				</td>
			</tr>
			<tr>
				<td></td>
				<td></td>
				<td>
					<?php $this->Form()->Input('submit') ?><br/>
				</td>
			</tr>
		</tbody>
		<tfoot/>
	</table>
	<?php $this->Form()->Finish($form_name) ?>
</div>
