<?php
/**
 * wizard-form.phtml
 * 
 * This is template of the Form of the Wizard.
 * Wizard is obsolete.
 * Please use the op-unit-selftest for the future.
 * 
 * @version   1.0
 * @package   op-core
 * @author    Tomoaki Nagahara <tomoaki.nagahara@gmail.com>
 * @copyright 2014 (C) Tomoaki Nagahara All right reserved.
 */
/* @var $this App */
if( OnePiece5::Admin() ){
	OnePiece5::StackError('Please use the op-unit-selftest for the future.','en');
}
?>
<style>

#form-wizard{
	margin: 1em;
	border: 0px solid #d8d7da;
	background-Color: #e8e2f3;
}

#form-wizard div.headline{
	padding: 0.5em 1em;
	background-Color: #583e8d;
	color: white;
	font-size: 150%;
	font-weight: bold;
}

#form-wizard div.content-area{
	margin:  0;
	padding: 0em;
	padding-left: 1em;
	padding-bottom: 1em;
	color: #2b1e44;
	border: 1px solid #d8d7da;
}

#form-wizard div.table{
	border: 0px dotted black;
    display: table;
}

#form-wizard div.tr{
	border: 0px dotted blue;
    display: table-row;
}

#form-wizard div.td{
	border: 0px dotted yellow;
    display: table-cell;
    vertical-align: top;
}

#form-wizard p.message{
	margin: 1em;
	color: #21045a;
	border: 0px solid #d8d7da;
	font-size: 125%;
}

#form-wizard div.content{
	margin: 1em;
}

#form-wizard div.tr{
	height: 1.6em;
}

#form-wizard div.th{
	margin-right: 1em;
}

#form-wizard input.op-input{
	border: 1px solid #4c455b;
	width: 16em;
	font-size: 11pt;
}

#form-wizard input.op-input-button{
	margin: 0;
	color: white;
	font-weight: bold;
	background-color: #653cb8;
	font-family: sans-serif;
}

#form-wizard input.op-input-button:hover{
	background-color: #7538ef;
}

#form-wizard input.op-input-submit{
	margin: 0.1em;
	padding: 0.2em;
}
		
#form-wizard .form-area{
	margin-left: 0px;
	width: 260px;
}
</style>
<div id="form-wizard" class="">
	<div class="headline">
		<span><?php print $title ?></span>
	</div>
	<div class="content-area" style="">
		<p class="message"><?php print $message ?></p>
		<div class="form-area table" style="">
			<?php $this->form()->Start($form_name) ?>
			<div class="table">
				<div class="tr">
					<div class="th">
						<?php $this->form()->Label($input_username) ?>
					</div>
					<div class="td">
						<?php $this->form()->Input($input_username) ?>
						<?php $this->form()->Error($input_username) ?>
					</div>
				</div>
				<div class="tr">
					<div class="th">
						<?php $this->form()->Label($input_password) ?>
					</div>
					<div class="td">
						<?php $this->form()->Input($input_password) ?>
						<?php $this->form()->Error($input_password) ?>
					</div>
				</div>
				<div class="tr">
					<div class="th">
					</div>
					<div class="td">
						<?php $this->form()->Input($input_submit) ?>
						<?php $this->form()->Error($input_submit) ?>
					</div>
				</div>
			</div>
		<?php $this->form()->Finish($form_name) ?>
		</div>
	</div>
</div>
